
`rust` 中没有异常。 `js` 中是 `try{} catch() {}`

Rust 中两种不同类型的错误处理：`panic` 和 `Result`。


## 捕获错误

处理 `Result` 类型最直接的方式是使用 `match` 表达式，这类似于其他语言中 `try/catch`：


## 错误传播

